title: Rise of the Machine
description: Documentazione ufficiale del progetto
remote_theme: just-the-docs/just-the-docs@v0.6.0
plugins:
  - jekyll-remote-theme

just_the_docs:
  mermaid:
    version: "9.1.3"