@startuml AiAbility

package model.strategy {
  abstract class AiAbility {
    +infectionBonus(): Int
    +sabotageBonus(): Int
  }

  class ImprovedInfection extends AiAbility
  class StealthSabotage extends AiAbility

  AiAbility <|-- ImprovedInfection
  AiAbility <|-- StealthSabotage
}

@enduml
