@startuml
package view {
  interface GameView {
    + renderGameTurn(worldState: WorldState): (Int, String)
  }

  object CLIView {
    + renderGameTurn(worldState: WorldState): (Int, String)
    - renderTurn(turn: Int): Unit
    - renderMap(worldMap: WorldMap): Unit
    - renderStatus(state: (Int, Int), abilities: Set[AiAbility]): Unit
    - renderProbability(Set[(String, Int, Int)]): Unit
  }

  GameView <|.. CLIView
}
@enduml
