name: Test PR from Develop

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  test:
    if: github.head_ref == 'develop'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Install sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Run sbt test
        run: sbt test
