name: Release on Tag

on:
  push:
    tags:
      - 'v*.*.*'  # Attiva il workflow solo su tag semantici

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Install sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Build fat jar (assembly)
        run: sbt assembly

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: target/scala-*/**/*assembly*.jar  # Adatta se usi un nome diverso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
